### ISSUE TITLE
Meaning of !!str |-

### ISSUE THREAD

**Issue by dbrazzeal** [usgs/ansible-rhel7-disa-stig-role#34]
In https://github.com/usgs/ansible-rhel7-disa-stig-role/blob/master/stig-rhel7-role.yml, why is this syntax used? !!str |-
I know it's used to define the many variables there but what does each of these symbols mean? I couldn't find any documentation about them.
!!
str
|
-
Thanks!

**Comment by emartinez-usgs** [comment]
I believe this is how the template came our of the scap-security-guide. Basically `!!str` provides unicode string characters. https://yaml.org/type/str.html

This, combined with `|-` provides multi-line, "chomped" strings. https://yaml-multiline.info/

**Comment by dbrazzeal** [comment]
Ok thank you

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
