### ISSUE TITLE
RHEL-07-010330: If three unsuccessful root logon attempts within 15 minutes occur the associated account must be locked.

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/ansible-rhel7-disa-stig-role#5]
**Discussion**
"By limiting the number of failed logon attempts, the risk of unauthorized system access via user password guessing, otherwise known as brute-forcing, is reduced. Limits are imposed by locking the account.

Satisfies: SRG-OS-000329-GPOS-00128, SRG-OS-000021-GPOS-00005"

**Justification**
DOI Default domain policy is 5.

**Comment by swwilson** [comment]
This one is not in the current stig-rhel7-role.yml at all.  Going to unassigned it, not sure if anyone is working on it or if it was purposely removed.

**Comment by glshank-usgs** [comment]
This fix will need to be added to our STIG since we need to modify the default (which is not to lock at all). I grabbed the code from the DISA yaml file and will attempt to make it work in our yaml file. Either way, this issue needs to remain open.
