### ISSUE TITLE
RHEL-07-010480: Systems with a Basic Input/Output System (BIOS) must require authentication upon booting into single-user and maintenance modes.

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/ansible-rhel7-disa-stig-role#7]
**Discussion**
If the system does not require valid root authentication before it boots into single-user or maintenance mode, anyone who invokes single-user or maintenance mode is granted privileged access to all files on the system. GRUB 2 is the default boot loader for RHEL 7 and is designed to require a password to boot into single-user mode or make modifications to the boot menu.

**Justification**
This deviation is required since implementing it will not allow us to remotely reboot servers since there is no way to enter a password. The servers do not have keyboards and there is nobody physically present to type it. The servers in question are in DOI approved data centers.

**Comment by swwilson** [comment]
Not set out of box, and not in the yml.

**Comment by swwilson** [comment]
My bad on the close and open.  Im using CentOS 7, and its not set on my machine.  However, I do see GRUB 2 is the default boot loader for RHEL 7. Figure probably best for someone else to review.
